### ISSUE TITLE
Small issue with `/gtr/place text`

### ISSUE THREAD

**Issue by mikkelee** [T-F-S/genealogytree#10]
Small issue: For some Danish places it is preferable to write "på" instead of "i" (_on_ instead of _in_).

I'm not sure there's a good clean way to solve that – is it possible to do something like this?

The default:
```latex
death = {DATE}{PLACE},
% would render as "† DATE i PLACE"
```
whereas the overriden version:
```latex
death = {DATE}{\overridePlaceText{p\protect\aa{} }{}PLACE},
% would render as "† DATE på PLACE"
```

Thoughts?

**Comment by T-F-S** [comment]
Currently, I do not see how this could be done as package option without changing a lot of things.

The place text is identical for each type of event, but is configurable for each language. A not-so-clever solution would be to redefine the danish language version to something like

```latex
place text={i/p\protect\aa{} }{},
```

For a package solution, we would have to have individual place texts for each event in every language...

If you look for a *personal* solution, you could overwrite `\gtrPrintPlace` which is located inside `gtrcore.node.code.tex` and is defined as:

```latex
\def\gtrPrintPlace#1{%
  \gtrkv@place@pre\csuse{gtrDB#1place}\gtrkv@place@app%
}
```

Here, `#1` is the event name, e.g. `death`. You could replace the code with distinction of cases for different events. Someting like:

```latex
% personal redefinition
\def\gtrPrintPlace#1{%
  % here: some case distinction according to #1 to print 'i' or 'på'
  \csuse{gtrDB#1place}%
}
```

**Comment by mikkelee** [comment]
Ah, thanks! The latter will work. I think I'll try with a local flag, something like (untested, pseudo-ish):

```latex
% redefinition
\makeatletter
\def\gtrPrintPlace#1{%
  \if%myoverride...%
  \csuse{gtrDB#1place}%
  \else%
  \gtrkv@place@pre\csuse{gtrDB#1place}\gtrkv@place@app%
  \fi%
  %reset override flag%
}
\makeatother

% usage in database:

death = {DATE}{\myoverride{}p\protect\aa PLACE},
```

So I can turn off the automatic pre/app insertion & just print out the place string verbatim when needed. It would also allow me to write something like "during a voyage".

I'll post what I come up with ~later today or tomorrow~ next week for others to peruse.

**Comment by mikkelee** [comment]
Hey, a bit late but I ended up doing this in my .sty file after importing:

```latex
%override
\def\gtrPrintPlace#1{%
  \IfBeginWith{\csuse{gtrDB#1place}}{!}{%
    \StrGobbleLeft{\csuse{gtrDB#1place}}{1}%
  }{%
    \gtrkv@place@pre\csuse{gtrDB#1place}\gtrkv@place@app%
  }%
}
```

Then if I write `!on an island` as a place it writes the string as-is without the pre-/postfixes (and without the exclamation mark, naturally).

It requires `xstring` because I'm very bad at LaTeX 😆

**Comment by T-F-S** [comment]
I am closing this issue (for now), since I do not see a common implementation for the package, but user specific configurations like you did for your application.

**Comment by mikkelee** [comment]
That is fine! :)

**Comment by T-F-S** [comment]
I translated your patch to LaTeX3. It does the same as your code, but `xstring` is not needed, because nowadays the LaTeX kernel contains all necessary tools:

```latex
\documentclass{article}
\usepackage[all]{genealogytree}
\begin{document}

\makeatletter
\ExplSyntaxOn
\cs_set_nopar:Npn \gtrPrintPlace #1
  {
    \tl_set_eq:Nc \l__getree_tmpa_tl { gtrDB#1place }
    \tl_if_head_eq_meaning:VNTF \l__getree_tmpa_tl !
    {
      \tl_tail:N \l__getree_tmpa_tl
    }
    {
      \gtrkv@place@pre \l__getree_tmpa_tl \gtrkv@place@app
    }
  }
\ExplSyntaxOff
\makeatother

\begin{tikzpicture}
\genealogytree [template=database pole]
{
  child{
    g{
      male,
      name       = {\pref{Charles} \surn{Smith}},
      birth      = {(caAD)1722}{London},
      baptism    = {1722-04-13}{!Ibid.},
      death+     = {1764-10-12}{}{killed},
      profession = {Copper smith, soldier},
      comment    = {Invented the square wheel},
    }
  }
}
\end{tikzpicture}
\end{document}
```
![grafik](https://github.com/T-F-S/genealogytree/assets/7982989/4e78621e-d362-4010-80e0-793f2031d14f)

**Comment by mikkelee** [comment]
Excellent, thanks!

I had considered rewriting it, as I've since learned expl3 --- but there are always things to do... ;)
