### ISSUE TITLE
Edge drawing: avoiding vertical shift

### ISSUE THREAD

**Issue by mikkelee** [T-F-S/genealogytree#12]
Hi

I have a tree where some persons are in two unions with children. I have used distances and such to move the nodes away from each other so the edges no longer overlap. However, they are still shifted vertically. Is this unavoidable or am I missing an option somewhere?

![skaermbillede 2017-11-23 kl 22 57 12](https://user-images.githubusercontent.com/644671/33189364-300429f0-d0a2-11e7-9e12-8d7dc948711f.png)

I can provide the database per email if requested.

**Comment by perstar** [comment]
This on the TeX stack exchange can be illuminating: https://tex.stackexchange.com/questions/254624/how-can-i-set-height-order-in-genealogytree-to-avoid-edge-crossings

**Comment by mikkelee** [comment]
Thanks, that works excellently, though I prefer to avoid shoving stuff around "by hand" (an option for allowing edges to overlap that assumes the author will position their tree correctly would be nice).

Just in time too, I'm delivering the final document to my grandma by hand tomorrow :)

**Comment by T-F-S** [comment]
Sorry for being too late to help you before you are delivering the final document.

Currently, there is no option to avoid the vertical shift which - in general - is an important feature.
To switch off this behaviour, a patch is needed. The following _**untested**_ patch should do the trick:

```latex
\makeatletter
\def\gtr@proc@@child@end{%
  \ifcsname gtr@fam@\gtr@currentfamily @g\endcsname%
  \else\gtr@error{No g-node in child family (\gtr@currentfamily)}{Every family needs a g-node}%
  \fi%
  \gtr@proc@pivot@reset%
  \letcs\gtr@gnode{gtr@fam@\gtr@currentfamily @g}%
  \csdef{gtr@fam@\gtr@currentfamily @offset}{0pt}%
  \ifcsname gtr@fam@\gtr@currentfamily @union\endcsname%
    \numdef\gtr@@parts{2}%
    \def\do##1{\numdef\gtr@@parts{\gtr@@parts+1}}%
    \dolistcsloop{gtr@fam@\gtr@currentfamily @union}%
    \dimdef\gtr@@dimfrac{1pt/\gtr@@parts}%
    \pgfmathqparse{\gtr@@dimfrac}%
    \csedef{gtr@fam@\gtr@currentfamily @frac}{0.5}% <------------------------------------
    \gtr@set@position@family{\gtr@currentfamily}%
    \let\gtr@@dimsumfrac=\gtr@@dimfrac%
    %
    \def\dodo##1{%
      \dimdef\gtr@@dimsumfrac{\gtr@@dimsumfrac+\gtr@@dimfrac}%
      \pgfmathqparse{\gtr@@dimsumfrac}%
      \csedef{gtr@fam@##1@frac}{0.5}%<------------------------------------------------
      \gtr@set@position@family{##1}%
      \ifcsname gtr@fam@##1@g\endcsname%
      \else%
        \listcseadd{gtr@fam@##1@par}{\gtr@gnode}%
        \gtr@add@gnode{\gtr@gnode}{##1}%
      \fi%
      \let\do=\dodo% loop-in-loop
    }%
    \let\do=\dodo%
    \dolistcsloop{gtr@fam@\gtr@currentfamily @union}%
  \else%
    \csdef{gtr@fam@\gtr@currentfamily @frac}{0.5}%
    \gtr@set@position@family{\gtr@currentfamily}%
  \fi%
  \let\gtr@tmp@nextwest=\@undefined%
  \let\gtr@tmp@nexteast=\@undefined%
  %
  \letcs\gtr@currentchildlist{gtr@fam@\gtr@currentfamily @patchi}%
  \letcs\gtr@currentparentlist{gtr@fam@\gtr@currentfamily @patpar}%
  %
  \ifdefined\gtr@currentchildlist%
    \let\do=\gtr@procchi@first@child%
    \dolistloop{\gtr@currentchildlist}%
    \gtr@proc@compute@pivotpoint@chi%
  \fi%
  \let\do=\gtr@procchi@first@parent%
  \dolistloop{\gtr@currentparentlist}%
  \gtr@proc@compute@pivotpoint@par%
  \ifdefined\gtr@currentchildlist%
    \dimdef\gtr@temp{\gtr@tmp@chipos@mid-\gtr@tmp@parpos@mid-\csuse{gtr@fam@\gtr@currentfamily @ps}}%
    \gtr@cont@shift{\gtr@currentparentlist}{\gtr@temp}%
  \fi%
}
\makeatother
```

This patch is quick-and-dirty, _**untested**_, and should be used just for testing.

I will see, if I can make something configurable for the next version (but not before 2018).

**Comment by mikkelee** [comment]
There's no rush! I got the document ready with @perstar's suggestion :)

**Comment by T-F-S** [comment]
Version 1.30 is public now and contains a new option `nullify edge level shift` which switches off the vertical shift globally, if needed.

**Comment by mikkelee** [comment]
Excellent, I'll experiment on a version of the document next week

**Comment by mikkelee** [comment]
This worked out with the 1.30 version, by the way :)
