### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by perstar** [T-F-S/genealogytree#13]
Here is a Swedish translation I have used for some time. Before submitting now I looked through gtrlang.german.code.tex to see if there are new strings to translate since I made this. The only new thing I saw was the typical date format, so I added that as well. I noticed that the current German file uses \protect a lot, and I don't understand why, so maybe this file should use that as well for the same reasons.

[gtrlang-sv.tex.txt](https://github.com/T-F-S/genealogytree/files/1522253/gtrlang-sv.tex.txt)

**Comment by T-F-S** [comment]
Thank your for providing this translation file.

The `\protect` is needed to avoid expansion, especially for `\dot` which is a macro that gets its definition depending on the usage context.

I would like to add this translation to the package. If you look into the translation files, you will find a line like

     %% Translation by XYZ <xyz at mail dot com>

Could you please add or post something, you would like to see for your person at this spot? Thank you.

**Comment by perstar** [comment]
`"Per Starbäck <per at starback.se>"` would be fine.
(BTW, you may have noticed that in a comment about typical date format I implicitly suggested two additional date formats.)

**Comment by T-F-S** [comment]
I noted the suggested additional date formats and put them on my TODO list.

Just one thing: The translation for the **Floruit** event is missing. Currently, I added 

     Floruit=floruit,

but you may want to add a Swedish translation for that, if appropriate.

**Comment by perstar** [comment]
I've only seen it as abbreviated "fl.". I don't think there is a widespread Swedish version.

**Comment by T-F-S** [comment]
The new version 1.30 contains the Swedish translation. Also, new date formats `d/m yyyy` and `yyyy d/m` are available.
