### ISSUE TITLE
"Arithmetic overflow" when dealing with a large tree

### ISSUE THREAD

**Issue by anderstood** [T-F-S/genealogytree#15]
When making a large tree, I faced the "Arithmetic overflow" error. I wrote a question on [tex.se](https://tex.stackexchange.com/questions/409395/arithmetic-overflow-error-with-genealogytree) with a MWE. It does not concern a bug in genealogytree, but it is still limitation. I am wondering if you have any ideas on how to overcome it.

**Comment by anderstood** [comment]
Oh, I just found this issue has already been raised: https://github.com/T-F-S/genealogytree/issues/8. Sorry I had not seen it before.

**Comment by anderstood** [comment]
Oh, I just found this issue has already been raised: https://github.com/T-F-S/genealogytree/issues/8. Sorry I had not seen it before. If you could however give a few indications on how to scale down the fonts, that would be useful, since they adjust automatically.

**Comment by T-F-S** [comment]
You need to have scalable fonts, e.g. `\usepackage{lmodern}` to replace the Computer Modern fonts by similar looking scalable ones.

Also, take a look at the `reduced` templates introduced with version `v1.21 (2017/09/15)`, e.g. `template=database pole reduced` (see Page 256ff of the documentation). You could use such a template or look at its source code to get ideas on how to brew your own style.
The general idea is to create miniature nodes to overcome the global size limitation...

**Comment by jrtaylor-3** [comment]
btw - the reduced format solved my big tree problem that I reported in #8.

**Comment by anderstood** [comment]
Great! Using `template=database pole reduced` solved my issue too.
