### ISSUE TITLE
How to crop images individually

### ISSUE THREAD

**Issue by azrdev** [T-F-S/genealogytree#17]
I just played with gramps5 beta and the new latex reports, noticing that images are included fully instead of cropped to the area defined in gramps (e.g. to only show a persons face): https://gramps-project.org/bugs/view.php?id=10494

Is it possible to crop images individually, and how? Didn't find it in the manual for 1.30

**Comment by T-F-S** [comment]
I am a complete novice to gramps and I was not able to produce some latex report with it yet. 
I installed GrampsAIO64-5.0.0-alpha3. Does this already contain the latex (genealogytree) export or do I have to install more?

Back to your question. Currently, there is no genealogytree database entry to provide options for the included images. But, this can be changed.

My first idea would be to add a new entry `imageopt` which can be filled with options for `\includegraphics`, e.g. something like

    imageopt={viewport=20pt 110pt 170pt 170pt,clip},

This option, possibly generated by gramps, would fill a macro `\gtrDBimageopt` which can be used for drawing.
Of course, all existing code for image inclusion would need to be adapted for using it.

The following is some test code based on an existing example. It zooms into the eyes of the `Carl_Friedrich_Gauss.jpg` image from the documentation.

```latex
\documentclass{article}
\usepackage[debug]{genealogytree}
\usepackage{lmodern}

\makeatletter
\gtr@db@new@store{imageopt}
\makeatother

\begin{document}

\begin{genealogypicture}[
  code={\tcbset{male/.style={colframe=blue,colback=blue!5},
    female/.style={colframe=red,colback=red!5}}},
  processing=database,
  database format=medium marriage below,
  node size=2.4cm,
  level size=3.2cm,
  level distance=6mm,
  list separators hang,
  name font=\bfseries,
  surn code={\textcolor{red!50!black}{#1}},
  place text={\newline}{},
  box={fit basedim=7pt,boxsep=2pt,segmentation style={solid},
    before upper={\flushleft\parskip1pt},
    \gtrDBsex,drop fuzzy shadow,
    if image defined={add to width=25mm,right=25mm,
      underlay={\begin{tcbclipinterior}%
        \ifdefvoid{\gtrDBimageopt}{\def\gtrDBimageopt{}}{}%
        \edef\x{\noexpand\path[fill overzoom image*={\expandonce\gtrDBimageopt}{\noexpand\gtrDBimage}]}%
        \x([xshift=-24mm]interior.south east) rectangle (interior.north east);
      \end{tcbclipinterior}},
    }{},
  },
  edges=rounded,
]
%%% the following is thought to be generated by gramps %%%%%%%
parent{
  g[id=GauxCarl1777]{
  male,
  name={Johann \pref{Carl Friedrich} \surn{Gau\ss{}}},
  birth={1777-04-30}{Braunschweig (Niedersachsen)},
  death={1855-02-23}{G\"ottingen (Niedersachsen)},
  profession={Mathematiker, Astronom, Geod\"at und Physiker},
  image={Carl_Friedrich_Gauss.jpg},
  imageopt={viewport=20pt 110pt 170pt 170pt,clip},% <-------------------
  }
}
\end{genealogypicture}
\end{document}
```

**Comment by azrdev** [comment]
> Does this already contain the latex (genealogytree) export or do I have to install more?

You have to install the LaTeX report addon "Sandclock Tree" (which is actually [GenealogyTree](https://github.com/gramps-project/addons/blob/master/gramps50/download/GenealogyTree.addon.tgz)), then you get a new submenu "Trees" in "Reports" with 4 report types which can be set to output `.tex` files.

Most of the code is actually not in the [addon](https://github.com/gramps-project/addons-source/tree/maintenance/gramps50/GenealogyTree), but in gramps core at [treedoc.py](https://github.com/gramps-project/gramps/blob/master/gramps/gen/plug/docgen/treedoc.py).

> My first idea would be to add a new entry imageopt which can be filled with options for \includegraphics, e.g. something like

To implement your proposal, gramps would probably add something like this to [treedoc.py](https://github.com/gramps-project/gramps/blob/master/gramps/gen/plug/docgen/treedoc.py#L458):

~~~python
def write_node():
  ...
  for mediaref in person.get_media_list():
    ...
    self.write(level+1, 'image = {%s},\n' % path)
    rect = mediaref.get_rectangle()
    if rect:
      self.write(level+1, "imageopt={viewport=%d %d %d %d,keepaspectratio},\n" % rect)
~~~

(`genealogytree` may want to set `keepaspectratio=true` by default)


However, I'm only a LaTeX user and by no means experienced in package writing, so of little help in that regard.

**Comment by T-F-S** [comment]
Thank you for looking into the gramps code for possible additions.

I think, I should take the first step and add some official `imageopt` option to `genealogytree`. I will have to do some more research on how to do this in a user friendly way.

Once such an option is implemented, the gramps export may be adapted to take advantage of it.

I put this on my list as feature request for `genealogytree`.

**Comment by azrdev** [comment]
thank you, sounds reasonable. If you need help and/or more input, don't refrain to ask!

**Comment by T-F-S** [comment]
Version 1.31 has two new database options `imageopt` and `viewport` which allow to crop images individually. Also, some more things are implemented (partially within `tcolorbox`) to ease the usage of such images within LaTeX source code.

**Comment by azrdev** [comment]
I tried adding `viewport=...`options from gramps code as I suggested, and I do get different results than before (when it would include the full images scaled down to fit into the box): The images are cropped, however not to the pixel rectangle I defined in gramps.
I tried using plain pixels in viewport, and suffixing them with `pt`, but for most images the visible part is just wildly off.
[Seems like](https://tex.stackexchange.com/q/21731) it is not trivial to specify viewport (or anything) in terms of image pixels in LaTeX, and we might be better off generating a cropped file from gramps and linking that one. My test PDF file also tells me that the original images are completely included instead of only the crop area, which lets the size explode for photographs. Also, it seems like spaces, underscores and other special characters in file paths/names are likewise non-trivial to handle in LaTeX, giving another argument to cropping from gramps.

What do you think?

TexLive 2017 from archlinux repositories
genealogytree 1.3.1 and tcolorbox 4.13 (in `/usr/local/share/texmf`)

**Comment by T-F-S** [comment]
The `viewport=...` options are options for `\includegraphics` from the standard `graphicx` package.
The four parameters are length parameters and they have to be given with respect to the `dpi` settings of the current image.

For example, a `jpg` image which is saved with `200 dpi` and a width of 1000 pixels is considered to have a width of `5in`. So, horizontal viewport parameters can be somewhere between `0in` and `5in`.

I guess (but do not know) that a Python script could extract the image resolution and compute `LaTeX` readable viewport arguments...(?)

The included images are always included in full (as you already observed). There is no way in reducing the image REALLY using `LaTeX` only (maybe with Lua?). The image is visually cropped, but not physically.

With `genealogytree 1.3.1`, individual VISUAL cropping is possible now. To get real cropping, one needs an external tool. The simplest way would be to do it with gramps directly during export. The same thing is true for path names as you already mentioned.
