### ISSUE TITLE
New feature request: Fanchart

### ISSUE THREAD

**Issue by datenschieber** [T-F-S/genealogytree#19]
Thomas,
thanks for the great genealogytree package!

I would be more than happy if you could fanchart output. I use this chart type often in my genealogy program. People really like these charts!

Thanks!

![fanchart](https://user-images.githubusercontent.com/30240661/42262166-b59fef32-7f6a-11e8-9929-0234daf07f2d.jpg)

**Comment by T-F-S** [comment]
It would be nice to have a fanchart output. The 'parent' grammar construct of `genealogytree` would be sufficient to hold the data for such a thing.

BUT, one would need a complete new graph drawing code ...

Actually, I already had this on my TODO list and I will keep it here. But I cannot promise that this feature comes soon or comes at all.

**Comment by T-F-S** [comment]
It took some time (actually, it took a long time), but with version `2.00 (2020/06/19)` there is a `fanchart` library. As usual, it contains a lot of customization options to draw graphs like the following:

![example](https://user-images.githubusercontent.com/7982989/85112805-85151f00-b216-11ea-86e8-b343bece95f3.jpg)

**Comment by jojomi** [comment]
Astonishing. Thank you very, very much! Like always also extensive documentation with great examples, chapeau!
