### ISSUE TITLE
The sample simple example doesn't work

### ISSUE THREAD

**Issue by nigelhorne** [T-F-S/genealogytree#22]
This is TeX, Version 3.14159265 (TeX Live 2019/dev/Debian) (preloaded format=tex)
(./in.tex
! Undefined control sequence.
l.1 \documentclass
                  {article}

**Comment by T-F-S** [comment]
Could you please provide the not working code? Is it an example from the documentation?

**Comment by nigelhorne** [comment]
Yes it is.

**Comment by T-F-S** [comment]
The documentation comprises 317 pages. I'm not able to help, if I do not know the code which did not work for you.

By the way: The error log hints that you may used `tex` instead of `pdflatex` for compilation (?!).

**Comment by nigelhorne** [comment]
I found a simple how to on https://tex.stackexchange.com/questions/296402/genealogytree-ancestor-approach - all is working now.
