### ISSUE TITLE
Children of In-Law Relatives

### ISSUE THREAD

**Issue by jojomi** [T-F-S/genealogytree#23]
I would like to know if there is a way of adding children to a node that is an in-law relative (hence no `g` node) himself.

Example:
```
\documentclass{scrartcl}
\usepackage[ngerman]{babel}
\usepackage[all]{genealogytree}

\begin{document}
  \begin{tikzpicture}
      \genealogytree[
      processing=database,
      template=database poleportrait,
      database format=full marriage below,
      ]{
        sandclock {
          child[] {
            g{ name = {Father} }
            p{ name = {Mother} }
            c{ name = {Son} }
          }
        }
      }
  \end{tikzpicture}
\end{document}
```

Would there be a way to make the son connected only to his mother, but not to the father (because he has another father who may or may not be part of the tree)?

It does not seem to be the right way to use `/gtr/add child` and in fact I am not even sure if the constraints of the package allow for it, but perhaps there is a tricky solution?

**Comment by T-F-S** [comment]
No, I fear, there is no direct support for children of in-law relatives. 

The tricky solution would be to create two `genealogytree`s and to connect them manually, analogous to

> 2.4 Tutorial: Descendants of the Grandparents (Connecting Trees)

**Comment by jojomi** [comment]
Thanks for your answer, I will have to see if I can connect a second tree there!

**Comment by mikkelee** [comment]
You can get pretty far by customizing options and combining trees:

![](https://i.imgur.com/mlQIVRT.png)

I pretty much only need to fix the z-ordering of the top marriages but that's a minor hitch, I think

**Comment by jojomi** [comment]
that looks great! Would you mind sharing the source for creating this (anonymized possibly)?

**Comment by mikkelee** [comment]
done via email
