### ISSUE TITLE
Using `\textsubscript{}` in place text

### ISSUE THREAD

**Issue by mikkelee** [T-F-S/genealogytree#25]
I would like to mark certain places with a subscript to disambiguate them with minimal typographical obtrusion. However, the below fails (with or without `\protect`):

```latex
birth = {1700}{Village\protect{\textsubscript{A}}},
death = {1700}{Village\protect{\textsubscript{B}}}
```

The error appears to pop up in some internal `microtype` code so I suppose it travels somewhat from its true origin:

```
./christen.database.graph:163: Undefined control sequence.
\MT@in@clist #1#2->\def \MT@res@a 
                                  ##1,#1,##2##3\@nnil {\ifx ##2\@empty \MT@i...
```

I have also tried `\textsuperscript` to the same result, though that clearly should work — after all `genealogytree` uses it to mark Gregorian/Julian caldendars...

**Comment by T-F-S** [comment]
Try to use the following:

```latex
birth = {1700}{Village\protect\textsubscript{A}},
death = {1700}{Village\protect\textsubscript{B}}
```

**Comment by mikkelee** [comment]
No luck. :-/

It actually seems to be triggered by some interaction between `microtype` and my override from #10 --- presumably due to its inclusion of `xstring`?

This morning, I've been trying to work out an alternate override that doesn't use anything not used by `genealogytree` already, but I'm not experienced enough to figure it out.

```latex
\makeatletter
\def\gprPrintPlaceOverride#1{
  \ifstrequal{\@car#1\@nil}{!}{% this turns to always be false, so it doesn't work...
    \@cdr#1\@nil%
  }{%
    \gtrkv@place@pre#1\gtrkv@place@app%
  }%
}
\def\gtrPrintPlace#1{%
  \expandafter\gprPrintPlaceOverride\csuse{gtrDB#1place}%
}
\makeatother
```

**Comment by T-F-S** [comment]
I guess that the expansion causes the error. Maybe, something like 

`\unexpanded{\protect\textsubscript{A}}` 

helps... 

If not, you should ask for help at https://tex.stackexchange.com, where many experts are.

**Comment by mikkelee** [comment]
I was unable to make it work with `\emph` + `\textsubscript`, however this works for now:

``` latex
% genealogytree override:
\makeatletter
\def\gprPrintPlaceOverride#1#2{%
  \ifstrequal{#1}{!}{%
    #2%
  }{%
    \gtrkv@place@pre {#1#2}\gtrkv@place@app%
  }%
}
\def\gtrPrintPlace#1{%
  \edef\@tmp@arg{\csuse{gtrDB#1place}}%
  \expandafter\gprPrintPlaceOverride\@tmp@arg%
}
\makeatother
```

And then typesetting places by changing the font instead of using latex's italic subscripts (actually I use `\VillageA`/`\VillageB` macros for convenience):

``` latex
birth = {1700}{Village{\fontspec{EB Garamond 12 Italic}[RawFeature=+sinf]A}},
death = {1800}{Village{\fontspec{EB Garamond 12 Italic}[RawFeature=+sinf]B}},
```

Anyway, it works...
