### ISSUE TITLE
Adding and using custom data in database

### ISSUE THREAD

**Issue by jojomi** [T-F-S/genealogytree#26]
I would like to know how to handle custom data in my genealogytree database.

For the first step I added the new key to the database entries:

```
p{
  birth- = {1872-10-11},
  death- = {1948-05-14},
  deathage = {75},
}
```

In the options I set `/gtr/database unknown key=save` according to p. 157 of the manual which should put the data to `/gtr/database/save/deathage`.

Now I am wondering how to access those data. How can I check if they custom key is set (`\gtrif…`?) and how can I print the content in a custom `database format`?

**Edit**: Testing with a minimal example makes me believe that my custom data are not available at `\grtDBdeathage` like other pieces of data.

Originally I posted this question [on Stack Exchange](https://tex.stackexchange.com/questions/460651/how-to-use-custom-database-entries-in-genealogytree-package).

**Comment by T-F-S** [comment]
See my answer at [Stack Exchange](https://tex.stackexchange.com/questions/460651/how-to-use-custom-database-entries-in-genealogytree-package/463514#463514).

**Comment by jojomi** [comment]
Thank you very much!
