### ISSUE TITLE
unknown key /tikz/fill overzoom DBimage

### ISSUE THREAD

**Issue by costaandrea** [T-F-S/genealogytree#27]
I am trying to compile the example in Section 2.3.4 on Overleaf:

```
\documentclass{article}

\usepackage[all]{genealogytree}
\usepackage{tcolorbox}

\begin{document}

\begin{genealogypicture}[
    processing=database,
    database format=medium marriage below,
    node size=2.4cm,
    level size=3.5cm,
    level distance=6mm,
    %...
    list separators hang,
    name font=\bfseries,
    surn code={\textcolor{red!50!black}{#1}},
    place text={\newline}{},
    date format=d/mon/yyyy,
    %...
    tcbset={male/.style={colframe=blue,colback=blue!5},
        female/.style={colframe=red,colback=red!5}},
    box={fit basedim=7pt,boxsep=2pt,segmentation style=solid,
        halign=left,before upper=\parskip1pt,
        \gtrDBsex,drop fuzzy shadow,
        if image defined={add to width=25mm,right=25mm,
            underlay={\begin{tcbclipinterior}\path[fill overzoom DBimage]
                ([xshift=-24mm]interior.south east) rectangle (interior.north east);
            \end{tcbclipinterior}},
        }{},
    },
]
sandclock
{
child{
    g[id=GauxCarl1777]{
        male,
        name={Johann \pref{Carl Friedrich} \surn{Gau\ss{}}},
        birth={1777-04-30}{Braunschweig (Niedersachsen)},
        death={1855-02-23}{G\"ottingen (Niedersachsen)},
        profession={Mathematiker, Astronom, Geod\"at und Physiker},
        image={Carl_Friedrich_Gauss.jpg},
    }
}
}
\end{genealogypicture}

\end{document}
```

But it throws an error: 
![error](https://user-images.githubusercontent.com/35759413/51048490-716f8d00-160e-11e9-8218-ba96636f2e96.PNG)
where line 46 is `\end{genealogypicture}`

Any idea on why and how to solve it? Is it a problem of the tcolorbox package?

**Comment by mikkelee** [comment]
I don't have an Overleaf account, but it works for me locally (if I supply an image).

The overzoom option was introduced in v1.31 (2018/04/17), probably Overleaf's packages are outdated.

**Comment by T-F-S** [comment]
I'm quite sure that [mikkelee](https://github.com/mikkelee) is right about the reason for the problem.

I also do not have an Overleaf account, but the log file should give the version number of the package, i.e. there should be a line like

    Package: genealogytree 2018/04/17 version 1.31 genealogy trees

Probably, you get a different line showing an older version.

**Comment by costaandrea** [comment]
Thank you both! 
Indeed, Overleaf's packages are outdated:
Package: genealogytree 2017/01/29 version 1.10 genealogy trees
Package: tcolorbox 2017/07/05 version 4.10 text color boxes
