### ISSUE TITLE
Trying to track down an issue

### ISSUE THREAD

**Issue by jrtaylor-3** [T-F-S/genealogytree#30]
I just updated MikTeX to the latest version and I am now getting the following errors at the end of every genealogytree.
Package xcolor Error: Undefined color 'tcbcol@back'
and
Package xcolor Error: Undefined color 'tcbcol@frame'

Are these genealogytree colors?

**Comment by T-F-S** [comment]
I am sorry, but I forgot to adapt `genealogytree` to the latest changes of `tcolorbox` :-(

The color names of `tcolorbox` became official and got new names. I will correct this for `genealogytree` very soon.

**Comment by T-F-S** [comment]
Should be solved with version `1.32 (2019-04-08)`

**Comment by jrtaylor-3** [comment]
Great!  How long does the update take to get pushed out to ctan?

**Comment by T-F-S** [comment]
It's already done and available from [CTAN](https://ctan.org/pkg/genealogytree) - thanks to the friendly and very fast CTAN team.
