### ISSUE TITLE
Adding edges between arbitrary nodes

### ISSUE THREAD

**Issue by mikkelee** [T-F-S/genealogytree#33]
I have a quite complex tree and would like to mark an "association" between nodes, eg. the blue "Jacob Borthig/Bortvig" nodes where the upper one is identical with _one_ of the lower ones. The tree is currently constructed from 3 graphs, I can provide the code via email if desired.

<img width="1163" alt="Skærmbillede 2019-09-21 kl  05 57 50" src="https://user-images.githubusercontent.com/644671/65367644-c9966e80-dc34-11e9-9d8f-95c26f2d9316.png">

I am considering a line from the upper JB that splits and goes to the lower JBs, with a short explanatory label. Is this possible?

PS: I have tried moving the children of Tobias Fleischer around so that this Jacob Bortvig was further to the left and closer to the others, but the affair-`union` with Anna Marie is making this difficult (its center/pivot is placed to the right of her marriage with Treschow — as the docs say `pivot shift` does not work for unions). Example:

<img width="764" alt="Skærmbillede 2019-09-21 kl  06 18 05" src="https://user-images.githubusercontent.com/644671/65367807-be910d80-dc37-11e9-84e2-dc72abd9b71b.png">

**Comment by T-F-S** [comment]
I fear, I have no good solution to untangle this graph.

Maybe, an option is to add quite thick but faint lines between the three JBs of your first picture in a background layer? This line could go behind the boxes for Georg Christian, etc.
That is no good solution, but just on idea.

**Comment by mikkelee** [comment]
Thanks! How do I add such a line? I've tried looking at the various `extra edges` options in the docs, but they don't seem to apply here.

And is there no way for putting a union to the left of a node?

**Comment by T-F-S** [comment]
No, I see only a manual way with TikZ code. On Page 91 of the documentation there is an example of some TikZ code using the node names generated by id values (`Jane1982` in the example).

**Comment by mikkelee** [comment]
Ah, thanks, that works :)

**Comment by mikkelee** [comment]
Just for curiosity's sake, it's becoming quite a cluster of similarly named people 😄 

https://drive.google.com/open?id=1eSb1Wn0jS3Gbfj-JKhZV1jBguSXXzk9u
