### ISSUE TITLE
Marriage lines overlapping with children connector lines

### ISSUE THREAD

**Issue by mavolin** [T-F-S/genealogytree#34]
![Screenshot from 2019-12-03 20-14-34](https://user-images.githubusercontent.com/48887425/70082230-343b3180-160a-11ea-981a-b38235a207a8.png)

As seen in the above picture, the auto-layout does not compensate for two siblings (Johann and Auguste), where both are married to someone, but only one has descendants. This results in the graph looking like four people had children together, instead of only Johann and Johanne.
In some cases I was able to fix this by inserting phantoms, but with genealogy tree as big, as the one I am editing now (311.4 cm * 53 cm) it is close to impossible to fix all overlappings, without breaking the tree when adding another descendant to the same generation.

**Comment by T-F-S** [comment]
This is a known and documented shortcoming of the implemented auto-layout algorithm. 
Currently, there is no solution with exception of manual insertion of phantom nodes.

For a future revision of the algorithm I can image that some kind of automatic phantom nodes are possible, but there are not plans (and time) at the moment. But I keep it in mind.

**Comment by mavolin** [comment]
Okay thanks! I'll stick to the phantom child's.

**Comment by T-F-S** [comment]
In the new `version 2.00 (2020/06/19)` there is a Section 5.15 'Childless Families' (from page 128).
There, the new automated insertion options for childless families are documented. The short story is that phantom nodes can now be added with one global key `insert phantom for childless families` for all families.
