### ISSUE TITLE
Suggestion: Non-Radial Fancharts

### ISSUE THREAD

**Issue by jojomi** [T-F-S/genealogytree#38]
Dear Thomas,

I just put the logic for building fancharts into my familybooks. Thanks a lot for that! They are beautiful and perfectly customizable as always.
The thing I thought about is, if we can use the available space better when kind of "flattening" that parent graph to a rectangular shape. I imagine n columns where each column separates to twice as many vertically stacked regions as the column before.

Did I overlook a possibility to create this efficient style by either tweaking fancharts or the general layout algorithm?

**Comment by T-F-S** [comment]
I think you look for something like the `ahnentafel 5` template (page 294 of the documentation):

![Bildschirminhalt](https://user-images.githubusercontent.com/7982989/104328519-2f72cd80-54ec-11eb-9e24-750fc2b4eb57.png)

It could be adjusted to be more rectangular, if needed.

**Comment by jojomi** [comment]
The new sytes a4paper 3/4/5 and display 16:9 3/4/5 are a welcome more neutral adition and kind of fit my initial idea here. Thank you for adding them!
