### ISSUE TITLE
`options for subtree` has no effect in v2.01

### ISSUE THREAD

**Issue by BertrandSim** [T-F-S/genealogytree#39]
Hello, I'm loving this package so far. Thanks for your work on this :)

One thing I've noticed is that `options for subtree` has no effect in the latest release (v2.01)
This is also seen in the manual, on pages 32, 33, and 107.
Could you have a look?

This seems to have worked in a previous release (v2.00).

(`options for family` and `options for node` are working as intended :))

**Comment by T-F-S** [comment]
Thank you for reporting. I can confirm the issue and I will look for the cause and for a solution.

**Comment by T-F-S** [comment]
I corrected the this bug with the new version `2.1.0 (2021-09-20)`. Should also become available on [CTAN](https://www.ctan.org/pkg/genealogytree) the next days.

**Comment by BertrandSim** [comment]
Thank you. I just checked, and the latest release is now available on CTAN :)
(It's not yet available on miktex, so I downloaded and updated your package manually). It works well!
