### ISSUE TITLE
other languages with special letters used to show up in pedigree

### ISSUE THREAD

**Issue by ten855** [T-F-S/genealogytree#40]
is the a possibility to use the pedigree in other languages like arabic I used \usepackage{arabtex} and wrote xxx.graph in arabic, but in don't show up.

**Comment by T-F-S** [comment]
I see no special reason why the package should not work with other languages. I do not know or use ArabTeX, but from quick googling I assume that text snippets like names have to be given inside `\RL{...}`, e.g.

```latex
child{
   g{\RL{....}}
   p{\RL{....}}
}
```

I assume that the `RLtext` environment may not able to contain a graph (but I really do not know), so every text may need to be given inside `\RL{...}` snippets.
