### ISSUE TITLE
French adjectives and gender

### ISSUE THREAD

**Issue by maieul** [T-F-S/genealogytree#5]
Hi,

in English we write
"A man  born on"
"A women born on"

But in French, and I think in other language, the adjective change with the gender.

"Un homme né en"
"Une femme née en"

**Comment by T-F-S** [comment]
Well, I guess you refer to the symbol legend. 
What do you suggest to change?

**Comment by maieul** [comment]
oh, it is only in a legend? Sorry, I don't use genealogytree, but I answered to a request of @dbitouze for checking French. I thought these terms were directly used in the tree.

The correct politic in France is to write or "né·e" or "né(e)" or né.e".
Personnaly, I prefer the first form, but I don't know if the middle dot is available in pdfLaTeX (it is in XeLaTeX)

**Comment by maieul** [comment]
Do you have a MWE of use of all the term defined in https://github.com/T-F-S/genealogytree/blob/master/tex/latex/genealogytree/gtrlang.french.code.tex? some of them should also be plural and not singular

**Comment by T-F-S** [comment]
You find the application of the terms inside https://github.com/T-F-S/genealogytree/blob/master/doc/latex/genealogytree/genealogytree-languages.pdf on page 4.

The middle dot should be no problem for LaTeX. I will see, what we can use here.
What texts of the "Symbol legend" should be changed to be more appropriate?

**Comment by T-F-S** [comment]
I uploaded a new version of https://github.com/T-F-S/genealogytree/blob/master/tex/latex/genealogytree/gtrlang.french.code.tex and https://github.com/T-F-S/genealogytree/blob/master/doc/latex/genealogytree/genealogytree-languages.pdf containing three replacement of "né" by "né·e". I'm sure that other terms have to be corrected in a similar way (?).

**Comment by maieul** [comment]
Yes, I will do it soon.

**Comment by maieul** [comment]
I have made the pull request.

An other problem, which is also in English is for "Partnership". For all the terme of relationship, you use an adjective for people concerned. Here, you use a substantive. For harmoniszation, you should use a adjective also for it.

In French, we have not really an adjectif for that. We have "concubins", but it means that people live in the same house, which is not necessary the cause for a "Partnership". We coulds harmonize by using the periphrastic form "en union libre" instead of "union libre".

**Comment by T-F-S** [comment]
OK, I will use "en union libre" instead of "union libre".

Finally, is "décédé le jour de sa naissance" correct or should it be "décédé·e le jour de sa naissance"?

**Comment by maieul** [comment]
"décédé·e le jour de sa naissance", you are right, I forget it.

**Comment by dbitouze** [comment]
Personally, I would write "né(e)" instead of "né.e"... I guess this could be discussed on French forums before setting things in tablets of stone :)

**Comment by maieul** [comment]
Un don't write "né.e" but "né·e".

That is a typicall "troll topics", but I said "personnaly".

My argumentair is here 
http://romy.tetue.net/feminiser-au-point-median

**Comment by dbitouze** [comment]
> Un don't write "né.e" but "né·e".

Ooops, sorry.

> That is a typicall "troll topics", but I said "personnaly".

So am I :)

>My argumentair is here
http://romy.tetue.net/feminiser-au-point-median

And, after reading, I agree with you. But maybe this could nevertheless be discussed on French forums.

**Comment by maieul** [comment]
> 
> 
> And, after reading, I agree with you. But maybe this could be nevertheless be discussed on French forums.
> 

if you want, do it ;-)
