### ISSUE TITLE
Externalization with an engine other than pdflatex

### ISSUE THREAD

**Issue by hzarnani** [T-F-S/genealogytree#50]
Hello,
I'd like to take advantage of the genealogytree package's support for externalization as described in Sec. 2.6.1.

I've noticed that the package invokes pdflatex to produce the graph in PDF format.

Is the assumption that the main document is also being compiled with pdflatex?  What if the main document is compiled with something other than pdflatex, e.g. xelatex?  Can I influence what engine and what arguments are used to produce the externalized graph?  Or is my best bet to implement my own externalization with, say, latexmk?

**Comment by T-F-S** [comment]
`pdflatex` is the default compiler for the externalized snippets independent from the compiler used by the main document.

But, you can change the snippet compiler using the `/tcb/external/compiler` option of tcolorbox. This could be done on a snippet by snippet base or globally for the whole document. I think you are looking for the latter. So, add the following line to your document preamble:

```latex
\tcbset{external/compiler=xelatex}
```

**Comment by hzarnani** [comment]
Thank you very much, @T-F-S.
