### ISSUE TITLE
Layout algorithm

### ISSUE THREAD

**Issue by alexreg** [T-F-S/genealogytree#53]
Hello. Could you kindly describe where the code for the layout algorithm is? What files and what macros in particular? This is not documented in the official documentation, and hard to grep.

**Comment by T-F-S** [comment]
> Hello. Could you kindly describe where the code for the layout algorithm is? What files and what macros in particular? This is not documented in the official documentation, and hard to grep.

The auto-layout algorithm is explained in chapter 14. Also, good parts of chapter 11 (debugging) are about the algorithm.

The main code parts for the algorithm are `gtcore.parser.code.tex`, `gtcore.contour.code.tex` and `gtcore.processing.code.tex`. More or less all macros inside are used for it...

**Comment by alexreg** [comment]
@T-F-S Thank you; that's very helpful. I'll have a dig around those files, and cross-reference with the docs.
